### PR TITLE
Add New Comment options

### PR DESCRIPTION
**Pull request by sorat0mo**
This pull request adds [commentbox.io](https://commentbox.io/) and [discussbot](https://comments.app/) in the comment section. Instructions to implement added in _config.yml

Below is a demonstration of the default settings:

CommentsBox:
Y0329_00001

DiscussBot:
Y0329_00001

### CODE REVIEW

**Comment by daattali** [comment]
Thanks for the initiative! I'd be happy to add CommentBox because they offer an extremely simple way to add comments, but there are already many comment systems and I don't see much offered by supporting discussbot as well. Could you remove discussbot? And please update the README as well in the relevant sections

**Comment by sorat0mo** [comment]
> Thanks for the initiative! I'd be happy to add CommentBox because they offer an extremely simple way to add comments, but there are already many comment systems and I don't see much offered by supporting discussbot as well. Could you remove discussbot? And please update the README as well in the relevant sections

Done!

**Comment by sorat0mo** [comment]
> Could you update the CHANGELOG file too please

Changelog updated as well

**Comment by daattali** [comment]
Thanks!

**Pull request merged**
