### PR TITLE
Enable plugin jekyll-paginate-v2 

### PR DESCRIPTION
**Pull request by sschwetz**
This paginator was released with Jeykll v3.0 and depreciated the original Jekyll-paginate. It is fully backwards compatible with the original paginator, with the only difference being that it needs to be enabled on pages that you wish to have paginated (i.e. /index.html).

This paginator has many more features than the original including the support for pages and posts, as well as categories, and tags.

It can also auto-generate category and tag pages.

### CODE REVIEW

**Comment by sschwetz** [comment]
I have set this to not be enabled by default, with instructions within _config.yml on how to enable it for non-gitubpages hosted/self hosted instances.

**Comment by daattali** [comment]
I appreciate the initiative, however I'm not convinced the added complexity in the config file outweighs the benefit. It seems like most of the changes here are commented out instructions (replace `jekyll-paginate` plugin with `jekyll-paginate-v2`, replace `paginate: 5` with a `pagination:` array, etc). Since I want to keep this as a GitHubPages-first theme and very beginner friendly, I constantly have to walk the delicate line between adding advanced features and not overwhelming beginners. I'd be open to hear a reason why this is very beneficial, but if you agree with me, I'd prefer to close this PR.

**Comment by sschwetz** [comment]
Yeah sounds good to me, I was just offering it up as it was something that I did on my own fork

**Comment by sschwetz** [comment]
I'll close this one off

**Comment by daattali** [comment]
I didn't even know about paginate-v2, I read it over and it sounds awesome. If github plans on ever supporting this , I'd love to make the switch. But I'll close this, thanks!

**Pull request closed without merging**
