### PR TITLE
Added my name in the list of personal websites

### PR DESCRIPTION
**Pull request by anuditverma**
added to the list www.anudit.in

### CODE REVIEW

**Comment by daattali** [comment]
Hi @anuditverma can you send this PR again once you have a few more posts? I want the list not to become too long, so I prefer to only add people if they have a lot of content

**Comment by anuditverma** [comment]
Ok @daattali , I am currently migrating some of the posts from my older blog, will let you know soon when its ready. Thanks.

**Comment by daattali** [comment]
Sounds good, thanks!

**Comment by anuditverma** [comment]
Hi again @daattali I have added few more posts, please have a look at www.anudit.in
Thank you.

**Comment by daattali** [comment]
Ok will add

**Pull request closed without merging**
