### PR TITLE
Fixes table borders for gist

### PR DESCRIPTION
**Pull request by OCram85**
I noticed a minor design problem while using github gists.
I don't know if you want the plugin included as default, but maybe you only want to merge the css changes.

### CODE REVIEW

**Comment by daattali** [comment]
You're learned a bit about me - I do prefer to not include the plugin by default, as part of my "keep dependencies minimal and the theme as basic as possible" philosophy :) I'll merge the CSS changes if you remove the others. Thanks!

**Comment by OCram85** [comment]
I removed the plugin dependencies and usage example.
It's ready to merge now. Thanks :1st_place_medal:

**Comment by daattali** [comment]
I can't merge because of a conflict in the CSS file. It's probably caused by your earlier contribution from today. Does github show you the conflict and give you a way to resolve it?

**Comment by OCram85** [comment]
Well I could try to resolve the conflicts but it fails because I don't have write access to your repo.
I'll try to pull the latest master changes first, and then update the diff.

**Comment by daattali** [comment]
If it doesn't work, I'll do it locally , let me know

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by OCram85** [comment]
Thanks for your patience. It should work now.

**Comment by daattali** [comment]
thank you

**Pull request merged**
