### PR TITLE
Added footer-links-active support to footer.html

### PR DESCRIPTION
**Pull request by sasivarnan**
Taken `footer.html` file content from the `master` branch and added it in `footer.html` of `gem` branch.

### CODE REVIEW

**Comment by daattali** [comment]
@sasivarnan thank you for this PR, but I actually left out `footer-links-active` on purpose. I think it was a mistake on the master branch because it is mostly redundant and just complicates the footer. If there's a link you want to show, you include it. If not, delete it or comment it out. I don't think there needs to be two parameters for each circle. When I first developed beautiful-jekyll there were only 5 circles so it wasn't too much, but now there are so many that I don't think it makes sense to have two parameters for each

@razu55 - were you asked to review today's 2 PRs?

**Comment by sasivarnan** [comment]
@daattali I felt the complication too. The reason why I raised this request is, the footer template in `gem` doesn't had `RSS` feed icon, which was available along with `footer-links-active` in master branch.

**Comment by daattali** [comment]
I understand. That really is the only disadvantage of the new system, and I did think about it but I assumed not enough people use RSS to make it important to support. But since it looks like someone does use it, I'll release a new gem later and support RSS (as a separate param though, not with the footer-links-active)

**Comment by sasivarnan** [comment]
@daattali. Thanks a lot. 😄

**Pull request closed without merging**
