### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by tae898**
This adds a small icon of your choice in the left corner of the browser tap.

### CODE REVIEW

**Comment by tae898** [comment]
Ah, obviously there is already an existing PR on this: https://github.com/daattali/beautiful-jekyll/pull/1234

My simple version works fine, though.

**Comment by daattali** [comment]
From my experience over the last 10 years, I've made many websites using beautifuljekyll and I never had to explicitly add the favicon location to the code. I simply place a favicon in the root, and it works (https://beautifuljekyll.com/faq/#favicon). Was there some change recently that makes this no longer the case? I'm trying to understand the need for this PR

**Comment by tae898** [comment]
Yeah somehow for my website, if I place `favicon.ico` in the root directory, it doesn't work. The favicon appears and disappears immediately from the web tab. I don't know why.

**Comment by daattali** [comment]
I'm wondering if it's a caching issue. Do you have a beautifuljeklly site, or can you create one, that has this issue? Where you have a favicon in the root and it doesn't automatically pick it up, I want to troubleshoot it

**Comment by daattali** [comment]
I've added favicon support with a simplified version. All you need to do is add a `favicon.ico` file to the root directory. Only `<link rel="icon" href="favicon.ico" />` gets added, because I'm not convinced of the benefit of all the other lines.

**Pull request closed without merging**
