### PR TITLE
[WIP] Source cleanup

### PR DESCRIPTION
**Pull request by OCram85**
## Blocked By
- ~#264~ ✅ 

# PR Scope
- adds basic editor config for developer using VSCode.
- adds .gitattributes to fore eol standards.
- (#260) Fix mixed indentation in files 

## Details
Each commit in this PR covers a touched file. Each file was changed to
- fix indentation (4 spaces per tab)
- liquid whitespace rendering

## Post Edit Checks
- compare rendered file output before and after edit for touched files.

## Content
- `./Includes`

| File | Status |
| :--- | :--------: |
| `disqus.html` | :white_check_mark: |
..

### Legend
- :white_check_mark: 
  - file touched, fixed, and checked
- :exclamation: 
  - :fire: :fire_engine: :boom: mhm, this didn't work
- :no_entry: 
  - nothing to change in this file. not touched, ignored in this PR.

### Workflow
- The PR Description gets updated by every additional commit
- No need to review the PR unless the [WIP] marker exists.

### CODE REVIEW

**Comment by daattali** [comment]
Great legend :)

**Comment by OCram85** [comment]
Uups, didn't replace all my placeholder :D

**Comment by daattali** [comment]
sfdsfsdsdf

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by OCram85** [comment]
Just updated the PR meta data to make clear this is blocked by an other issue/task or PR. 🔥

**Comment by daattali** [comment]
I appreciate your organization, it really helps make my life much easier!

**Comment by OCram85** [comment]
It think I'm going to close this PR and convert it to some kind of *Umbrella Task*. The planned changes within this PR would be to big to handle as one PR. So I prefer to deal with lots of small changes. To keep track on this the *Umbrella Task / Milestone* could help.

The other reason is the amount of time it needs to touch all files. It forces me to merge changes from master from time to time...

I transfer the meta content of this PR into the new Issue to avoid confusion.

**Comment by daattali** [comment]
Good point re: having to merge from master because I keep making changes.... sorry about that! FYI there are no more planned changes in the next little while. But yes, feel free to make it work in whatever way is best for you

**Comment by OCram85** [comment]
It turned out to me much more work for cleaning up the indentation and whitespace problem as I thought in the beginning. I would rather work on #254. But I fear to create a bigger mess if I start working on this first.

**Comment by daattali** [comment]
Feel free to do 254 and forget about the formatting PR if you prefer. Any
kind of help is appreciated!

On Oct 20, 2017 02:31, "Marco Blessing" <notifications@github.com> wrote:

It turned out to me much more work for cleaning up the indentation and
whitespace problem as I thought in the beginning. I would rather work on
#254 <https://github.com/daattali/beautiful-jekyll/issues/254>. But I fear
to create a bigger mess if I start working on this first.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/daattali/beautiful-jekyll/pull/261#issuecomment-338118136>,
or mute the thread

**Comment by OCram85** [comment]
Closed - Work will go on with #270

**Pull request closed without merging**
