### PR TITLE
Add a favicon

### PR DESCRIPTION
**Pull request by cogniti**
Thank you for this beautiful theme.
This pull request add a favicon feature.

### CODE REVIEW

**Comment by daattali** [comment]
Have you tried simply placing a favicon in the root directory? You don't need to specify it in the html, jekyll will automatically pick it up

**Comment by cogniti** [comment]
I will try your way again.

**Comment by cogniti** [comment]
I have tried it on new OS on VirtualBox because of the image cache.
Placing a favicon.png in the root directory doesn't appear in Firefox 48.0.2(Bookmakr toolbar or a tab) on Linux.
Please check this point.

**Comment by daattali** [comment]
Oh I see, I prefer to stick with the more widely supported favicon.ico (instead of png) which is usually recommended, does it also not recognize that?

**Comment by cogniti** [comment]
I'll test within 24 hours.

2016. 9. 13. 오전 8:28에 "Dean Attali" <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
You are right. I'm sorry to have taken your time.
Thank you.

**Pull request closed without merging**
