### PR TITLE
Allow to disable the round avatar

### PR DESCRIPTION
**Pull request by gpotter2**
- adds ability to turn off the round avatar

### CODE REVIEW

**Comment by gpotter2** [comment]
I didn't realize there is no CI on this project

**Comment by daattali** [comment]
Good point, a CI (Travis? Github actions?) could be a good addition

**Comment by daattali** [comment]
Can you just add an entry to the CHANGELOG file please? Then this will be merged

**Comment by daattali** [comment]
Have you tested this code?

I just tried it and I'm getting 3 similar errors

> Liquid Warning: Liquid syntax error (line 174): Expected dotdot but found pipe in "(site.round-avatar | default: true)" in css/main.css

Does it work for you without errors?

**Comment by daattali** [comment]
I need to revert this PR, it doesn't work correctly. If I remove the avatar-round field from the config file, it isn't round. Did you test this before submitting?

**Comment by gpotter2** [comment]
Sorry for that. I couldn't publish the 2 PRs at the same time. That's why I didn't want to split them.

**Pull request merged**
