### PR TITLE
Add conditional avatar

### PR DESCRIPTION
**Pull request by hristoyankov**
Hi, I'm using beautiful-jekyll for my personal site (https://hristoyankov.com) and I love it. However, I needed a way to show my avatar only in the "About me" and in the future "Personal projects" and therefore added liquid param for this.

NB: This is my first pull request I may have made some mistakes. Thank you for your understanding in advance!

### CODE REVIEW

**Comment by daattali** [comment]
That's a beautiful PR :) You even added it to the documentation :+1:

A few notes

1. Did you test this on blog posts as well as regular pages?  GitHub Pages upgraded to a new version of Jekyll this week, and I've noticed a lot of problems with using the `page.` variable for parameters that are declared in a layout. So please confirm that you can turn avatars on/off on blog posts as well as pages

2. In the readme, change `show_avatar` to `show-avatar`

3. Change the readme description to:

> If you have an avatar configured in the `_config.yml` but you want to turn it off on a specific page, use `show-avatar: false`. If you want to turn it off by default, change `shot-avatar` to `false` in the file `_layouts/default.html` and then you can selectively turn it on in specific pages using `show-avatar: true`

**Comment by hristoyankov** [comment]
Hi, thanks for the feedback!

I have it working for me on http://hristoyankov.com/aboutme/ vs the rest of the site. However, it's not quite like you describe it. If I want it turned off by default I should remove it from the default.html and add it only to the layouts or specific pages.

I guess I'm not explaining it very well but I'm pretty new to jekyll and liquid and I'm not sure whether they have proper parameters shadowing.

I'd like to tackle it a little bit more and will send you an update.

**Comment by hristoyankov** [comment]
Hi again!

I didn't knew about the `defaults: ` section in the `_config.yml`. I've added the `show-avatar: true` param there and updated the `README.md`. As for the `page` variable and jekyll 3.0 - all metadata in the layout front matter is now stored in the `layout` variable. Here you can see the result:

http://hristoyankov.com/beautiful-jekyll/ , http://hristoyankov.com/beautiful-jekyll/featured-users/ -> the `page` layout doesn't display the avatar

However, `post` layout and **only** `Getting started` display the avatar:
http://hristoyankov.com/beautiful-jekyll/getstarted/
http://hristoyankov.com/beautiful-jekyll/2015-02-26-flake-it-till-you-make-it/

PS: I've just noticed the updated README on the beautiful-jekyll repo. Best of luck with your thesis and sorry for bothering!

**Comment by daattali** [comment]
Putting it in the config.yml does sound better.  But now the second half of the description needs to reflect that, so:

> If you want to turn it off by default, locate the line `show-avatar: true` in the file `_config.yml` and change the `true` to `false`; then you can selectively turn it on in specific pages using `show-avatar: true`.

Then I'll merge :)

**Comment by hristoyankov** [comment]
Done!

**Comment by daattali** [comment]
thanks @hristoyankov

**Pull request merged**
