### PR TITLE
adds site reference

### PR DESCRIPTION
**Pull request by OCram85**

### CODE REVIEW

**Comment by daattali** [comment]
Hi @OCram85 thanks for the PR!

How long has your site been up? (I ask because I try to only publish blogs that have been using the theme for at least several months, because any less means that people are still highly likely to change to a different theme)

**Comment by OCram85** [comment]
Well, I started my blog a month ago. I've customized it a bit and will try to add some card layouts. Do you mind if I create pull requests for the changes I did?

**Comment by daattali** [comment]
Of course - if there's anything you think would be beneficial to many others, and is generalizable (not specific to you), then please do make PRs. What are the things you want to add?

**Comment by OCram85** [comment]
I'm thinking about using the jekyll categories for separating post series. Therefore I would like to add a bootstrap  based card layout for the pagination preview.

I've already did some css changes:
- added boxes for notes, warning, error messages
- fixed the table layout for post with github gists. There was a problem with the default table / tr border
- added piwik support
- added robots.txt
- minor fixes in header / meta fields

**Comment by daattali** [comment]
Could you show me on your website what functionality you want to port over? I try to make sure anything in this theme is easy to use for noobs and uncomplicated

**Comment by OCram85** [comment]
For sure. Give me some time to finalize it and I will contact you either  to take a look at my website or create another pull request per feature.

btw... Thanks for this awesome theme. You really did a great job!

**Comment by daattali** [comment]
Thank you, I spent so many weekends locked in my room determined to make
this nice and as easy as possible for anybody to use. Never thought it
would be used by anyone so it's really nice to see so many forks :)

**Comment by daattali** [comment]
Looks like you're quite committed to this theme. If you still think you'll stick around with it for a while, let me know and I'll add you now. If in the future you ever change, please try to let me know!

**Comment by daattali** [comment]
@OCram85 let me know if you're ready to add this :)

**Comment by OCram85** [comment]
I'm absolutely ready for this change :) 👍

**Comment by daattali** [comment]
If in the future you change, try to let me know please

**Pull request merged**
