### PR TITLE
I'm entierly new to github. I 'm not quite sure how to commit changes to this website from github.com.

### PR DESCRIPTION
**Pull request by thesandmanman**
Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.

If your intention is to submit a Pull Request, please describe what your pull request achieves.

Thank you!

### CODE REVIEW

**Comment by thesandmanman** [comment]
I'll explain in detail -
I updated the _config.yml and commit, but the changes didn't reflect on the github.io website.
I even tried to add a new post on the _posts folder.
But even after committing changes the website doesn't change.
What am I doing wrong ? Could you help.

**Comment by colynn** [comment]
@thesandmanman  You need fork  `daattali/beautiful-jekyll` firstly, then do your custom change.

You can get more detailed guidance from [readme.md](https://github.com/daattali/beautiful-jekyll#build-your-website-in-3-steps).

**Comment by JackGruber** [comment]
Hi 

- your _config.yml has an error on line 4.
grafik
- A Pull request to the original repo is unnecessary.

**Comment by thesandmanman** [comment]
@colynn I did fork the repo first though... it even says "forked from daattali/beautiful-jekyll" in my repo. I'll try redoing it.
Thanks

**Comment by thesandmanman** [comment]
@JackGruber the line 4 is just the title: <blog name>
About the pull request, I understand.
I will try again.
Thanks

**Pull request closed without merging**
