### PR TITLE
Updated to Font Awesome v5, added docker social icon

### PR DESCRIPTION
**Pull request by shyd**
Hi,
as promised in #324, here is my PR with all needed updates in order to use font awesome v5. I also added docker to the SocialNetworks.yml
Some icons changed a bit since older versions in size and the icon itself.

Cheers 🍻

### CODE REVIEW

**Comment by daattali** [comment]
From the 2-minute research that I did, it looked like you don't **have to** switch to SVG. I prefer to stick with the old version for now that doesn't require a javascript file and handles it at in css. Are there big advantaged to moving to svg?

**Comment by daattali** [comment]
From the 2-minute research that I did, it looked like you don't **have to** switch to SVG. I prefer to stick with the old version for now that doesn't require a javascript file and handles it at in css. Are there big advantaged to moving to svg?

**Comment by shyd** [comment]
Agree. But:
Using js is the recommended method to use v5. The big advantage I see, is that there is only one request needed to get the fonts: fetching the js-file. When using css there are more requests needed, because the browser needs to fetch the webfonts in addition to the css-file.
Nevertheless using css doesn't require as much traffic as using js. Where js includes every icon, css downloads needed fonts only.

My PR works either way, just include css or js:

```
common-ext-css:
  - "//use.fontawesome.com/releases/v5.0.6/css/all.css"

common-ext-js:
  - "//use.fontawesome.com/releases/v5.0.6/js/all.js"
````

**Comment by abelcheung** [comment]
I'm personally switching to JS version for testing:

Pro: It offers some cool effect not available with webfont + CSS, like arbitrary resizing, rotating, and icon masking (allowing background image to show through icon layers, for example)

Con: It can slow down IE to a crawl with certain usage ([specifically with CSS pseudo elements][1]),
which has no fix for now, except using webfont + CSS version

The choice to make really depends on target audience; but for generic usage I'm siding with webfont version too.

[1]: https://stackoverflow.com/questions/50976897/fontawesome-5-svg-icons-data-search-pseudo-elements-causes-100x-slowdown-in-ren

**Comment by daattali** [comment]
Thanks for your input @abelcheung . For now I'll stick with this as you said, may revisit in the future

**Pull request closed without merging**
