### PR TITLE
Markup home page content lists and tags as lists

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
This PR wraps the posts list on the home page in a list tag to fix it's semantics. The same fix has been applied to the list of tags for a post.

### CODE REVIEW

**Comment by daattali** [comment]
Thanks, do you have a version of beautifuljekyll that uses this exact PR so that I can test it visually?

**Comment by JeffersonBledsoe** [comment]
Hi @daattali. I'm not personally using this theme but know somebody who was looking into it. Here's a couple of screenshots showing the before & after of the change using the example content in this repo. The visual changes are minimal (and can be completely removed if desired).

## Before

Screenshot of the beautiful-jekyll theme without the new markup


## After

Screenshot of the beautiful-jekyll theme showing a difference in list separator styling with the new markup

**Comment by daattali** [comment]
Other than adding `role="list"` in order to fix what you mentioned on Safari, is it necessary to make the other changes of adding ul/li tags?

**Comment by JeffersonBledsoe** [comment]
@daattali The markup makes it clearer for non-visual agents (such as screen readers, SEO engines or bots) what the markup is. For example, screen readers will announce the user is in a list and provide functionality for navigating lists. I need to do some more research on whether the tags should be in a `<ul>`, but the list of pages almost certainly should be

**Comment by daattali** [comment]
I would need to do some rigorous testing on this to make sure it doesn't affect the UI. Have you tested this? Also, there's a typo `ole` instead of `role`

**Comment by daattali** [comment]
I've made a few changes to make usre the styling is not changed, merging now. Thanks!

**Pull request merged**
