### PR TITLE
update jQuery

### PR DESCRIPTION
**Pull request by OCram85**
Updates jQuery as first preperation step for GDPR compliance.

### CODE REVIEW

**Comment by abelcheung** [comment]
Well, IMHO many of the resources (JQuery, Bootstrap etc) could have been offloaded to CDN instead of being bundled and served from Github. Usage of FontAwesome is already done in this way. That could acutally improve performance as well, since multiple resources are loaded from different locations in parallel.

**Comment by abelcheung** [comment]
Please forget previous comment since I haven't checked out the umbrella task at that time. Looks like more than technical issue have to be considered as well.

**Comment by abelcheung** [comment]
Confirmed, this patch can't be applied. Bootstrap 3.x explicitly don't support JQuery 3, only accepts &ge; 1.9.1 and 2.x.

**Comment by daattali** [comment]
Can't be applied *until bootstrap is updated

**Comment by danielmpetrov** [comment]
> Confirmed, this patch can't be applied. Bootstrap 3.x explicitly don't support JQuery 3, only accepts ≥ 1.9.1 and 2.x.

[Boostrap 3.3.7](https://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/) introduced support for JQuery 3, so updating to the latest Boostrap 3 version (currently v3.4.1) will do the trick.

**Comment by daattali** [comment]
Closing this for now, if bootstrap will be upgraded then we can revisit

**Pull request closed without merging**
