### PR TITLE
Adds page configuration for description

### PR DESCRIPTION
**Pull request by lexicalunit**
Sometimes a page subtitle isn't substantive enough to be a good value for a meta description. An optimal length for meta descriptions is usually around 150 characters, which might be too long for a pithy page subtile. In this case I added a `site.description` override that will be used only if provided. Otherwise we fallback to using the subtitle.

### CODE REVIEW

**Comment by lexicalunit** [comment]
Getting a weird dependency error in the tests. Any ideas @daattali?

**Comment by daattali** [comment]
Regarding the build error, no idea. @gpotter2 any clue?

**Comment by daattali** [comment]
If I don't set a description on a page, but I have a description defined in the config.yml, then it will always override the subtitle, right?

**Comment by lexicalunit** [comment]
As far as I know: No. It's my understanding that `page.description` would only ever come from page front matter. So under no circumstances could anything in `_config.yml` override a page subtitle.

**Comment by daattali** [comment]
I just tested this, and you're correct.  `page` params do not inherit from `site`. Thanks

**Comment by gpotter2** [comment]
He was faster than me and spotted the missing dependency :-)

**Comment by daattali** [comment]
Thanks for taking a look anyway!

**Pull request merged**
