### PR TITLE
fix google scholar link construction (#1187)

### LINKED ISSUE #1187: Google Scholar link construction is broken
When I use `google-scholar: "4ODJ78oAAAAJ"`, it routes to a non-existent page: https://scholar.google.com/4ODJ78oAAAAJ.

I fixed this by setting `google-scholar: "citations?user=4ODJ78oAAAAJ"`, which correctly routes to https://scholar.google.com/citations?user=4ODJ78oAAAAJ

# Details
* I have merged the latest `master` into my fork
* My fork: https://github.com/crypdick/crypdick.github.io
* My site: richarddecal.com

### PR DESCRIPTION
**Pull request by crypdick**
Closes #1187  and supersedes  #1188

### CODE REVIEW

**Comment by daattali** [comment]
Thanks! Can you add an entry in the CHANGELOG file. This is a BREAKING CHANGE because anyone who previously made google scholar work (by adding that entire string) will now need to edit the parameter

**Comment by daattali** [comment]
@crypdick do you want to finish this PR?

**Comment by crypdick** [comment]
@daattali sorry I'll get to it when I can, busy with work. feel free to take over if you wish

**Comment by daattali** [comment]
@crypdick do you want to return to this?

**Comment by crypdick** [comment]
ty for getting it over the finish line @daattali

**Pull request merged**
