### PR TITLE
delete sample posts

### PR DESCRIPTION
**Pull request by talvandijk**

### CODE REVIEW

**Comment by daattali** [comment]
Did you mean to make this a pull request?  I purposely have sample posts so that people can see how to write new posts

**Comment by talvandijk** [comment]
No. Sorry. It's a mistake. How can I revert this?

**Comment by daattali** [comment]
There's nothing to "revert" as nothing was done. You simply made a pull request, which means "hey, look at the changes I made, why don't you incorporate them?" and I rejected it

**Comment by talvandijk** [comment]
Okay. By the way, great job. I really like the design.

**Comment by daattali** [comment]
thanks!

**Comment by daattali** [comment]
toda!

**Pull request closed without merging**
