### PR TITLE
Badge functionality to layout/post.html

### PR DESCRIPTION
**Pull request by yonicd**
add badges functionality to post.html and instructions in readme yaml section

### CODE REVIEW

**Comment by daattali** [comment]
I just tested this, but it looks like some CSS (or perhaps Javascript that loads CSS?) is needed to make the github buttons work. Did you ever add any css/js for this, other than the HTML? Currently it's just literally printing the words "Star" "Issue" "Follow" "Watch" etc

**Comment by yonicd** [comment]
it should have to need any additional css/js since it works off the same idea of adding a badge to any GH md page.

**Comment by daattali** [comment]
I implemented this on my site successfully. I used the other library, the one that uses iframes directly, because it's way faster.  ghbtns.com

I also changed the `gh_repo` and `gh_badge` to `gh-repo` and `gh-badge` to be more consistent with other YAML params. And I added a bit of CSS so that on small screens the buttons will be one per line because it looks awkward otherwise. Here are the changes:

https://github.com/daattali/daattali.github.io/blob/master/_layouts/post.html#L11-L32
https://github.com/daattali/daattali.github.io/blob/1c9ff4d6ce9d49af84eaf4d4a9cbfb3533319dac/css/main.css#L441-L449


Let me know if you want to update your PR or if I should just do it (I don't mind doing it myself, but it means your name will not show up in the git history)

**Comment by daattali** [comment]
oh right, I actually prefer to exclude those, because I don't want the theme to have R-specific features

**Comment by yonicd** [comment]
no problem. i'll keep it on mine (it's an option anyways that doesnt always have to be used)

**Comment by yonicd** [comment]
the second link is to a different branch so the main.css is different than to the one the PR is connected to.

**Comment by yonicd** [comment]
updated PR to iframes

**Comment by daattali** [comment]
yes the css link is on my own website which has diverged significantly. but it shouldn't matter, it's just 2 css rules that need to copied over

**Comment by daattali** [comment]
Nevermind, you did see it and incorporate it. Thanks.

Can you remove the code for CRAN (as opposed to commenting it out), and also the documentation for this should be within the YAML frontmatter parameters table. There's a big table in the readme with all the available params. Then ready to merge :)

**Pull request merged**
