### PR TITLE
Adds support for meta keywords

### PR DESCRIPTION
**Pull request by lexicalunit**
Adds support for meta keywords. It will use the page keywords if provided, otherwise fallback to site level.

### CODE REVIEW

**Comment by daattali** [comment]
Good idea! Right now there is no keywords support at all. Do you strongly feel the need for both side-wide and page-specific keywords?

**Comment by lexicalunit** [comment]
My use case is only for site-wide but I thought I'd toss in page-specific support just in case. I don't feel strongly about it.

**Comment by daattali** [comment]
Let's keep it simple at site-wide only. I'm trying to active fight getitng a huge laundry list of options.

**Comment by daattali** [comment]
Clarification: I'm sure there will be *some* people who want even more customization per-page. But having keywords globally should be what the vast majority of users use, and I prefer simplicity over catching 100% of usecases

**Comment by lexicalunit** [comment]
Right on. Updated.

**Comment by daattali** [comment]
The documentation and the README need to be updated accordingly

**Comment by lexicalunit** [comment]
Oops! My bad.

**Pull request merged**
