### PR TITLE
Jekyll code change in Staticman script

### PR DESCRIPTION
**Pull request by VincentTam**
The separation of Jekyll logic from the Staticman JS script has received positive feedback in https://github.com/daattali/beautiful-jekyll/issues/518#issuecomment-510610064.  I've made this PR to put my words into deeds.

@abelcheung Please review this PR to see if this fits into your suggestions in the linked issue.  I've changed `_includes/staticman-script.html` to `assets/js/staticman.js`.  If Staticman is enabled, the comment submission form will be loaded in `_posts`, but not site pages like `aboutme.md`.  If I could grant you write permission to this PR, I would definite do so.

* * *

Edited: testing site at https://git.io/bjsm18

Screenshot from 2019-07-23 13-08-21

### CODE REVIEW

**Comment by VincentTam** [comment]
Update: On the demo site https://git.io/bjsm18 (source: https://git.io/bjsm0), the HTML source code for each post no longer contains form action URL.  It's now set in `js/staticman.js`, see 
19c9d06.

```diff
diff --git a/js/staticman.js b/js/staticman.js
index 3d6a0a726bd..7472722cd7d 100644
--- a/js/staticman.js
+++ b/js/staticman.js
@@ -1,3 +1,7 @@
+---
+layout: null
+---
+
 (function ($) {
   var $comments = $('.js-comments');
 
@@ -6,9 +10,14 @@
 
     $(form).addClass('disabled');
 
+    {% assign sm = site.staticman -%}
+    var endpoint = '{{ sm.endpoint | default: "https://staticman3.herokuapp.com/v3/entry/github/" }}';
+    var repository = '{{ sm.repository }}';
+    var branch = '{{ sm.branch }}';
+
     $.ajax({
       type: $(this).attr('method'),
-      url: $(this).attr('action'),
+      url: endpoint + repository + '/' + branch + '/comments',
       data: $(this).serialize(),
       contentType: 'application/x-www-form-urlencoded',
       success: function (data) {
```

**Comment by VincentTam** [comment]
@daattali Continued from https://github.com/daattali/beautiful-jekyll/issues/518#issuecomment-515727509:

> Is this a concern that you've observed in practice?

Correct me if I've misunderstood anything.  I suppose you mean the spam problem, which is observed in a host of GitHub repo using Staticman like https://github.com/einsteinpy/blog.einsteinpy.org/pull/25, https://github.com/hashtafak/hashtafak.github.io/commits/master, etc.  As IT isn't yet my field, I can't verify the info in [this article about dynamical form action URL setup](https://www.willmaster.com/library/manage-forms/bot-block-for-forms.php), but that's the 2nd best I can do for users who don't use reCAPTCHA for whatever reasons.

**Comment by daattali** [comment]
Is there a reason for users not to use reCAPTCHA, or is it just the fact that it's a little bit of extra work upfront?

**Comment by VincentTam** [comment]
As a reCAPTCHA user, I can't speak for them, but I can try providing some possible reasons by searhcing ["google is evil site:github.com"](https://duckduckgo.com/?q=%22google+is+evil%22+recaptcha+site%3Agithub.com&ia=web):

- https://github.com/Chocobozzz/PeerTube/issues/1721
- https://github.com/m-cat/bytedude.com/issues/44

Some FOSS users who support [*De-google-ify Internet*](https://degooglisons-internet.org/en/) will, very likely, avoid reCAPTCHA.

I've never used Akismet, so I can't comment on Staticman's Akismet integration, which @staticmanlab, the default Staticman bot in this theme, didn't touch.

Fighting spam bot is a formidable task.  The server logic is out of the scope of a static theme.  However, if [the linked article in my previous comment](https://www.willmaster.com/library/manage-forms/bot-block-for-forms.php) about the behavior of spam bots is (empirically) true, then I have to move the form action URL to JavaScript in order to stop some of these bots.

Here's an example of inclusion of form action URL in JavaScript instead of HTML: https://team-parallax.com/use-selfhosted-staticman-with-gitlab-1
Due to the complexity of its source code, web developer tools (in any modern browser) are needed to analyse what it's doing.  It's `<form>` element has two events: `onSubmit` and `submit`.  I've just followed the JavaScript containing the first event and found this POST URL by searching `e.apply(`, which is the heart of `function` that handles the event `onSubmit`.

Note: reCAPTCHA would never put a end to this issue.  [This Jekyll blog on GitLab](//zcrc.me) ([source](https://gitlab.com/pcercuei/pcercuei.gitlab.io)) has enabled reCAPTCHA (and even a GUI Markdown editor :memo: with :eye: preview.  Nonethess, it's still spammed by human users :crying_cat_face:.

I'll try sparing some time to learn Node.JS and statistical learning to come up with a way to fight this, but this can be long.

**Comment by abelcheung** [comment]
Looks good

**Pull request merged**
