### PR TITLE
adds boxes

### PR DESCRIPTION
**Pull request by OCram85**
Summary
======

- updated fontawesome ref to 4.7
- converted tabs into 4 spaces
- added `boxes.css` because I didn't want to mess with the `main.css`
- added draft post with instructions how to use the boxes.
  - mentions 3 different ways how to use boxes. I you add the jekyll plugin for fontawesome gh-pages won't built the site.

Testplan
=====

- merge the changes
- run `bundle exec jekyll serve --drafts`
- open [local jekyll site](http://127.0.0.1:4000) and navigate to the `Remarkup` post

### CODE REVIEW

**Comment by daattali** [comment]
Hi @OCram85, this PR seems incomplete and doesn't really explain what boxes are -- or am I just missing something? :)

**Comment by OCram85** [comment]
The boxes adds the possibility for bloggers to highlight easily important areas of  an post. You can choose between a `note`,  `warning` or `error` message box.
Therefore you can use [add custom css classes to an element](https://kramdown.gettalong.org/quickref.html#block-attributes) like this:

```
{: .box-note}
**NOTE:** This should be rendered as a note
```
```
{: .box-warning}
**WARNING:** This should be warning box
```

```
{: .box-error}
**WARNING:** This should be highlighted as error!
```

**Comment by daattali** [comment]
Oh cool! I like it :) So this works with github pages (without local ruby installation)? Can you post link to live example, on your website I suppose, to see it in action

**Comment by OCram85** [comment]
Yes it works with github pages. The fontawesome jekyll plugin is optional. It would simplify the usage for the icons with a custom liquid tag.
I used the boxes in my recent blog post [here](https://ocram85.github.io/2017-07-19-ReadOnly-Class-Properties/).

**Comment by daattali** [comment]
Since I want to keep this theme as minimal and beginner-friendly as possible, I'd like to avoid adding features that require plugins. But I do like the boxes. Would you mind adding the boxes css into the main.css file, and showing an example of using the box in one of the existing sample posts?

**Comment by OCram85** [comment]
I'm glad you like it. Should I do the changes within this pull request?

**Comment by daattali** [comment]
Yes you can update this pull request

**Comment by OCram85** [comment]
Done. This should work now as expected 😸

**Comment by daattali** [comment]
Thanks!

**Pull request merged**
