### PR TITLE
fix(#744): Escape special characters in title

### PR DESCRIPTION
**Pull request by f-squirrel**
Fixes https://github.com/daattali/beautiful-jekyll/issues/744

### CODE REVIEW

**Comment by daattali** [comment]
Thanks!

Are you sure we want that in _includes/header.html as well? Did you have an example of what happens currently on the page and how it's fixed with your PR?

**Comment by f-squirrel** [comment]
I am not, I've only made sure that special characters used in `title` are escaped whenever is possible.
Share card before the fix:
Screen Shot 2020-11-25 at 14 31 01
After the fix:
Screen Shot 2020-11-25 at 14 34 38

From an HTML perspective, all `"` used in title are replaced with `&quote;`.

The link to the fixed post:
https://ddanilov.me/the-state-of-std-optional-after-move/

**Comment by daattali** [comment]
Yes I agree this is needed in the meta tags. But the other parts of the code that you changed, unless they're tested and you know that they're needed, we should remove them.

**Comment by f-squirrel** [comment]
@daattali , The link I've posted contains a page with the fix implemented. Hence it is tested.
If the title contains other special characters like `<`, `>` or `&` and the header.html file is not changed, then the title is shown only partially.
Example:
`title: The <moving" truth behind std::optional`
Is rendered as following:
Screen Shot 2020-11-26 at 14 55 03
I think it might be safer to change the `_includes/header.html` as well.
WDYT?

**Comment by daattali** [comment]
Are you having issues with anything besides double quotes?

Because I just spent some time reading on this, and it seems that for share cards, double quotes should be avoided, which means this isn't a beautifuljekyll issue. If you google for this, you'll find that it's generally a bad practice to include quotes in the title/description, and if you do have to use quotes then you should use single rather than double quotes.

**Comment by daattali** [comment]
Regardless, I do agree with stripping html tags and escaping in the title/description meta tags. But either way, a double quotation mark in the title is not generally a good idea.

In the title of the page, currently HTML tags do work if you put quotes around. For example `title: "one <i>two</i> three" will show the word two in italics. I don't know if this behaviour is good or not - should titles be disallowed from using html tags? What do you think?

**Comment by f-squirrel** [comment]
@daattali , agreed, HTML tags are a legitimate part of the title.
I've updated the PR(removed the changes in the `_includes/header.html` file.

Thank you for the detailed expalnation.

**Comment by daattali** [comment]
Could you add an entry in the CHANGELOG please

**Comment by f-squirrel** [comment]
Done.

**Pull request merged**
