### PR TITLE
Itch.io social link

### PR DESCRIPTION
**Pull request by Emaleth**
Added Itch.io to social links

### CODE REVIEW

**Comment by daattali** [comment]
Have you tested this to make sure the fontawesome version used in this theme has this icon?

Please also add an entry in the CHANGELOG file

**Comment by Emaleth** [comment]
Added entry in CHANGELOG.md (under unreleased) but cant find FA in head or anywhere, could you tell me where to find info / tell what version you use?

**Comment by Emaleth** [comment]
Ok, found it. Yes, it is in version 5.

**Comment by daattali** [comment]
Have you tested this?

**Comment by Emaleth** [comment]
https://emaleth.dev
https://github.com/emaleth/emaleth.github.io
(keep in mind it's just social include, its still of original repo via remote_theme, but since other files were not modified it should suffice.

**Comment by daattali** [comment]
Thanks!

**Pull request merged**
