### PR TITLE
Add options to have menus and submenus at multiple levels in navbar

### PR DESCRIPTION
**Pull request by marste**
Like:
- menu
	- aaa
	- bbb
		- ccc
		- ddd

### CODE REVIEW

**Comment by daattali** [comment]
Did you look at the code changed in this PR? It looks like the entire codebase has changed. I think it's because you might be merging from a different branch that is very outdated. Could you do a new PR with only the changes that are actually relevant to this feature?

**Comment by daattali** [comment]
@marste based on your description of this PR, it's definitely a worthwhile feature! Let me know if you can re-do the PR with more specific changes

**Comment by marste** [comment]
Sorry @daattali, maybe I was wrong. I was hoping someone could implement this feature.
I'm unfortunately unable to develop it.

**Comment by daattali** [comment]
Oh, I understand. I was very excited because this is a difficult feature to implement elegantly, and I thought this was your attempt at implementing it.

If you want to make a feature request, you can [open an issue](https://github.com/daattali/beautiful-jekyll/issues). What you did here is called a Pull Request, which is something you do when you want to make an improvement to the code that you're using. I'm closing this because obviously you didn't mean to send your code.

**Pull request closed without merging**
