### PR TITLE
Moving search to it's own file.

### PR DESCRIPTION
**Pull request by monksy**
Speed up search and reduce page sizes.

https://github.com/daattali/beautiful-jekyll/issues/1284

Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.

If your intention is to submit a Pull Request, please describe what your pull request achieves.

Thank you!

### CODE REVIEW

**Comment by monksy** [comment]
image

**Comment by monksy** [comment]
@daattali

**Comment by daattali** [comment]
Thanks for the suggestion! I've been thinking about this for a while and while I do really agree with the idea, there's one problem that makes it difficult for me to accept this PR. 
Anyone who uses this theme as a `remote_them` or a ruby gem will not have access to the json file you created, and they'll be required to manually add that file. There are currently only a handful of files that behave this way, and I try to stay away from that as much as possible, because each one of these cases adds more friction. Do you think there's a way to achieve the same goal but without creating a file that users will have to create manually?

**Comment by daattali** [comment]
@monksy ping :)

**Comment by ccorsi** [comment]
@daattali I agree with you that this is a good idea but the implementation requires a better solution.  I think that the generated json file should be placed within the assets directory, specifically within a data subdirectory of assets.  Since your theme includes this as part of your distribution then this solution will work when using the gem or remote_theme feature.

**Comment by daattali** [comment]
Implemented in e6fc968cbdd592ed73ed49eb622cbf32ed67728c

Thanks @ccorsi for your help

**Pull request closed without merging**
