### PR TITLE
Improved pull request for "Add readtime #594"

### PR DESCRIPTION
**Pull request by rubyreads**
@daattali -- it took me a while to figure this out; I ended up starting over with a new fork to make things clean. I originally had trouble because of nested if statements and improperly adding the config param to work elsewhere as an invalid  `site.readtime` instead of making it able to work with `page.readtime` (creating a failure to build). However, I caught these mistakes and the code ended up working on each post.

**Note**: Readtime will only appear on each post if enabled in _config.yml; it will not appear on index.html (that is, the list of posts). People may want the readtime to appear next to the post date on that list though. I attempted to add the code to that page but I was unable to make it work; it is beyond my limited experience.

### CODE REVIEW

**Comment by memoriesus** [comment]
Yeah actually if the readtime display globally, that's great

**Comment by daattali** [comment]
Gracias @rubyreads it looks great!

A few more things before I can merge this please:

1.The spacing/indentation of the added code in `header.html` is incorrect - can you fix
2. Can you replace the middot with some space instead, like 10 pixels margin. The dot right after the date looks a bit weird to me.
3. On mobile, the date+readtime line becomes too long, and the readtime is broken up into two lines. It would be better if on mobile it would simply be on a new line. So: on mobile it goes on a new line, on larger screens it gets a left margin. This would mean that you likely need to place it in its own span

Sorry for making you do extra work, this theme is used by a lot of people and I try to make sure every code that goes into it will be perfect :)

**Comment by rubyreads** [comment]
@daattali -- gracias 🙂. I meant to comment back sooner. First change would be a quick fix but the second/third (for a span and margin) may take me a while... or maybe someone else can help? I used a mobile phone to work on this pull request; it is all I have access to during our local government stay-at-home order or self-quarantine. It may not be lifted till next month. My smaller screen doesn't show the readtime being broken and I'm thinking I might end up not changing the code correctly (until I can test it under another system that can better emulate other screen sizes).

**Comment by daattali** [comment]
Don't worry about it - if you look at previous issues and pull requests, some of them take weeks or even months. And sometimes it takes me weeks to look over a pull request.

Take your time.

**Comment by daattali** [comment]
Regarding smaller screens: changing the appearance of something based on screen width is done in css using `media` queries. Look at the current main.css file and you'll see lots of `media` around - they're used to make text appear differently depending on screen size. You'll be able to figure it out:)

**Comment by daattali** [comment]
@rubyreads let me know if you ever come back to this

**Comment by daattali** [comment]
@rubyreads I'm closing this PR in favour of the new one that @Mutmatt is working on. Thanks for getting this started!

**Comment by rubyreads** [comment]
@daattali -- cool, thank you. I was limited by my phone, but I'm glad I could contribute. Looking forward to seeing the new one finished. Thanks @Mutmatt 🖒

**Comment by Mutmatt** [comment]
> @daattali -- cool, thank you. I was limited by my phone, but I'm glad I could contribute. Looking forward to seeing the new one finished. Thanks @Mutmatt 🖒

Glad to help carry it across the finish line! 🎉 OSS 🎉

**Pull request closed without merging**
