### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by gpotter2**
- adds a CI
- I made sure not to hardcode anything (thus the long command), to make sure this will still work on forks

### CODE REVIEW

**Comment by gpotter2** [comment]
This is now working: https://github.com/gpotter2/beautiful-jekyll/runs/599083553?check_suite_focus=true
@daattali

**Comment by daattali** [comment]
Thanks. I don't think this would have caught the previous problem, because it didn't actually break the jekyll build, it just didn't have the expected results. But still useful

**Comment by daattali** [comment]
@gpotter2 Could you help me troubleshoot why the CI is failing for seemingly no reason? According to https://github.com/daattali/beautiful-jekyll/actions?query=actor%3Adaattali it was working fine last week, and my commit today which only changed a few characters in a CSS file and the CHANGELOG somehow broke it. I looked at the log and I see that a process exited with an error but I don't see any error messages. Do you know how to troubleshoot this?

**Comment by gpotter2** [comment]
Sure.

Another thing, please never @ me in the commit names (or anyone else). I get **TONS** of github notifications each time a user fails his merge commit...

**Comment by daattali** [comment]
Oh geez I didn't know,  sorry. I hope you found out how to unsubscribe from those notifications

**Comment by gpotter2** [comment]
Yeah it's alright :smile:
I've done the PR in https://github.com/daattali/beautiful-jekyll/pull/644

**Pull request merged**
