### PR TITLE
updating

### PR DESCRIPTION
**Pull request by brophyj**
updating

### CODE REVIEW

**Comment by daattali** [comment]
you need to do this on your project , not this one

**Comment by brophyj** [comment]
very sorry, wasn’t paying attention

James (Jay) Brophy MEng MD FRCP(c) FACC FCCS PhD
Professor of Medicine & Epidemiology (McGill)
Royal Victoria Hospital
1001 Decarie Blvd Room C04.5011
Montreal (Qc) H4A 3J1
Telephone: 514 934-1934 ext. 36771, Fax: 514 843-1493
e-mail: james.brophy@mcgill.ca<mailto:james.brophy@mcgill.ca>

On Jan 5, 2018, at 5:31 PM, Dean Attali <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #296<https://github.com/daattali/beautiful-jekyll/pull/296>.

**Comment by daattali** [comment]
No worries!

**Comment by brophyj** [comment]
Hi

As I found your template to be very useful and informative, i was wondering if I might prevail on you for a question.
I have written a short book in rmarkdown using bookdown. I have uploaded all the html files to my GitHub webpage. I created a post saying the book is available with a link to the index.html file. When the link is clicked it shows the html code and not the formatted book.
Do you have a quick resource that i might consult to fix my issue.
Thanks & Happy New Year

JB

James (Jay) Brophy MEng MD FRCP(c) FACC FCCS PhD
Professor of Medicine & Epidemiology (McGill)
Royal Victoria Hospital
1001 Decarie Blvd Room C04.5011
Montreal (Qc) H4A 3J1
Telephone: 514 934-1934 ext. 36771, Fax: 514 843-1493
e-mail: james.brophy@mcgill.ca<mailto:james.brophy@mcgill.ca>

On Jan 5, 2018, at 5:33 PM, Dean Attali <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries!

**Comment by daattali** [comment]
Sorry I'm not sure the exact problem. I get dozens of personal requests per
day so it's difficult for me to answer to each individual question
unfortunately. I suggest asking on twitter/stackoverflow/somewhere else
online.

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by brophyj** [comment]
will do
thanks anyway

James (Jay) Brophy MEng MD FRCP(c) FACC FCCS PhD
Professor of Medicine & Epidemiology (McGill)
Royal Victoria Hospital
1001 Decarie Blvd Room C04.5011
Montreal (Qc) H4A 3J1
Telephone: 514 934-1934 ext. 36771, Fax: 514 843-1493
e-mail: james.brophy@mcgill.ca<mailto:james.brophy@mcgill.ca>

On Jan 5, 2018, at 5:41 PM, Dean Attali <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry I'm not sure the exact problem. I get dozens of personal requests per
day so it's difficult for me to answer to each individual question
unfortunately. I suggest asking on twitter/stackoverflow/somewhere else
online.

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Pull request closed without merging**
