### PR TITLE
Added a hacker news link.

### PR DESCRIPTION
**Pull request by monksy**
This PR creates a Hackernews share button to the posts. The SVG comes from HN it's self.

Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.

If your intention is to submit a Pull Request, please describe what your pull request achieves.

Thank you!

### CODE REVIEW

**Comment by monksy** [comment]
image

image

**Comment by monksy** [comment]
@daattali

**Comment by daattali** [comment]
Thanks for the initiative!

I prefer not to use a custom file, because it adds one additional dependency. Fontawesome does have an icon for hackernews so I'd rather use that (even though yours is prettier). Also, please disable it by default.

**Comment by daattali** [comment]
@monksy ping

**Pull request closed without merging**
