### PR TITLE
layout fix for #1235

### PR DESCRIPTION
**Pull request by dagnelies**
For #1235

### CODE REVIEW

**Comment by daattali** [comment]
Does this fix also take into account still supporting the original reason for https://github.com/daattali/beautiful-jekyll/commit/ba46ef8abd1e2aea30c04b633a7fcdbb31e122b2 ? In other words, is https://github.com/daattali/beautiful-jekyll/issues/576 still fixed as well? Or does this PR only fix the current issue?

**Comment by dagnelies** [comment]
Yup. Both fixed

**Comment by daattali** [comment]
Great, I'll test it later, thanks! Looking at the code changes, I'd like to change the `<main>` to a `<div>`, because there are already divs further down that have `role="main"`, and I don't think it's good practice to have `<main>` and inside of it another div with `role="main"`

**Comment by dagnelies** [comment]
Sure. Do as you like. Please pay attention that the CSS rule `body > main { flex: 1 }` should only target the main area of the body, not the nav header or footer.

**Comment by dagnelies** [comment]
you could even drop this outer "main" container directly and apply the `flex:1` to the main content container.

**Comment by daattali** [comment]
@dagnelies Thanks for all your work on this. I just updated the layouts so that every page now has a `<main>` tag - however, it's not in the exact same hierarchical location within the DOM on each page type. Would applying `flex:1` to the main tag  would solve the problem?

**Comment by dagnelies** [comment]
The CSS rule `body > main { flex: 1 }` makes the main grow to fill the empty page if necessary. As long as there is a `<main>` directly under the `<body>`, anywhere, what's after the main will appear at the bottom.

**Pull request closed without merging**
