### PR TITLE
Adding option for Medium Social Link at footer 

### PR DESCRIPTION
**Pull request by zenithexpo**
#783 Submitting this PR so that the user will have an option to link their Medium profile on the website's footer.

### CODE REVIEW

**Comment by daattali** [comment]
Do you have an example where I can see this in action, in your repo?

**Comment by zenithexpo** [comment]
Yes, I have added this option for my website, but the changes are a little different there.  
I have added changes there for custom Medium URL [https://github.com/zenithexpo/zenithexpo.github.io/commit/697d75f789bc72702fcf04d4fe5b81860886d32b](url)
[https://github.com/zenithexpo/zenithexpo.github.io/commit/c6927ed203b3953b7c856b36d71a9a05db6a0a95](url)
How changes look on footer [https://dikshaverma.me/](url)

**Comment by daattali** [comment]
Hmm none of those URLs seem to work... can you show make a new clone of this repo with exactly this PR in it, as a test that this works? A lot of times in the past people submitted tiny PRs that seemed to be ok but one character was missing and it wouldn't work. So I want to make sure every piece of code is tested exactly as it is in the PR

**Comment by zenithexpo** [comment]
https://github.com/zenithexpo/zenithexpo.github.io/commit/697d75f789bc72702fcf04d4fe5b81860886d32b
https://github.com/zenithexpo/zenithexpo.github.io/commit/c6927ed203b3953b7c856b36d71a9a05db6a0a95
https://dikshaverma.me/
Now, these URL works, sorry for entering the wrong format.
Okay, I will do that test and update.

**Comment by zenithexpo** [comment]
Hello, back again! Tested this on the forked repo, on the new testing branch separately.
Original forked repo, branch name - testing: https://github.com/zenithexpo/beautiful-jekyll/tree/testing
In action (on footer) : http://dikshaverma.me/beautiful-jekyll/

**Comment by daattali** [comment]
Looks good! Can you just add this to the CHANGELOG please

**Comment by zenithexpo** [comment]
Sure, I will do that, Should I update under the Unreleased version?

**Comment by zenithexpo** [comment]
Updated The CHANGELOG.

**Comment by daattali** [comment]
Thanks!

**Pull request merged**
