### PR TITLE
added page titles in social share buttons

### PR DESCRIPTION
**Pull request by DirectorX**

### CODE REVIEW

**Comment by daattali** [comment]
Thank you, but I'm pretty sure this will break sharing. The Twitter one might work, but the others require a URL and by adding some text to the URL field it'll break

**Comment by DirectorX** [comment]
@daattali works well
have a look [here](https://infernus.gitlab.io/blog/2016/08/%D7%94%D7%92%D7%9C%D7%99%D7%95%D7%9F-%D7%94%D7%A9%D7%91%D7%A2%D7%99%D7%9D-%D7%95%D7%97%D7%9E%D7%99%D7%A9%D7%94-%D7%A9%D7%9C-Digital-Whisper-%D7%A9%D7%95%D7%97%D7%A8%D7%A8/)

**Comment by daattali** [comment]
Clicking the Twitter share link on that page works for me. Clicking the Facebook/Linked In links do not work for me.

**Comment by DirectorX** [comment]
right, i should add `{{ url_param_escape }}`

**Comment by daattali** [comment]
if you get it working on a different page, do let me know

**Comment by DirectorX** [comment]
after a little research seems like tweeter are the only one that allow it

**Comment by daattali** [comment]
Right, that makes sense, because for Twitter you're telling it what to include in the "tweet" text, whereas the other sites are asking for a URL specifically , not free form text

**Comment by DirectorX** [comment]
i did `git commit --amend` and re write the history, now the commit is 2c062bcb22ee93e7c4145c10fc580d88c0943e34, please reopen this issue and review the changes.

**Comment by daattali** [comment]
This PR cannot be re-opened.  Can you please submit a new pull request with the new changes

**Pull request closed without merging**
